const fs = require('fs'), path = require('path'), vm = require('vm'), assert = require('assert');
const source = fs.readFileSync(path.join(__dirname, '../AccessibleVision/Services/NativeLocationBridge.swift'), 'utf8');
const script = source.match(/static let script = #"""([\s\S]*?)"""#/)[1];
const messages=[], timers=new Map(), listeners={};let nextTimer=0;
const window={webkit:{messageHandlers:{nativeLocation:{postMessage:m=>messages.push(m)}}},addEventListener:(name,fn)=>listeners[name]=fn};
const context={window,navigator:{},setTimeout:(fn,delay)=>{timers.set(++nextTimer,{fn,delay});return nextTimer;},clearTimeout:id=>timers.delete(id)};
vm.createContext(context);vm.runInContext(script,context);
const geo=context.navigator.geolocation;
assert.equal(messages.length,0,'Opening app must not ask for location');
let result=null, failure=null;
geo.getCurrentPosition(p=>result=p,e=>failure=e,{enableHighAccuracy:true,timeout:12000});
assert.equal(messages[0].type,'get');assert.equal(messages[0].highAccuracy,true);
assert.equal(timers.size,0,'Permission prompt must not consume acquisition timeout');
window.__accessibleVisionLocationResult({id:'1',ready:true});
assert.equal(timers.size,1);
const timerId=[...timers.keys()][0];
window.__accessibleVisionLocationResult({id:'1',ready:true});
assert(timers.has(timerId),'Unrelated authorization callback must not reset timeout');
const position={coords:{latitude:31.2,longitude:121.4,accuracy:6},timestamp:Date.now()};
window.__accessibleVisionLocationResult({id:'1',position});
assert.equal(result,position);assert.equal(timers.size,0);
assert.equal(messages.at(-1).type,'clear');
let updates=0;
const id=geo.watchPosition(()=>updates++,e=>failure=e,{timeout:15000});
window.__accessibleVisionLocationResult({id:String(id),ready:true});
window.__accessibleVisionLocationResult({id:String(id),position});
window.__accessibleVisionLocationResult({id:String(id),position});
assert.equal(updates,2);
geo.clearWatch(id);assert.equal(timers.size,0);
window.__accessibleVisionLocationResult({id:String(id),position});assert.equal(updates,2);
geo.getCurrentPosition(()=>assert.fail('denied must not succeed'),e=>failure=e);
window.__accessibleVisionLocationResult({id:'3',error:{code:1,message:'denied'}});
assert.equal(failure.code,1);assert.equal(failure.PERMISSION_DENIED,1);
geo.getCurrentPosition(()=>assert.fail('timeout must not succeed'),e=>failure=e,{timeout:10});
window.__accessibleVisionLocationResult({id:'4',ready:true});
[...timers.values()][0].fn();assert.equal(failure.code,3);
const watch=geo.watchPosition(()=>{},()=>{});
listeners.pagehide();assert.equal(messages.at(-1).id,String(watch));
assert(source.includes('requestWhenInUseAuthorization()'));
assert(source.includes('message.frameInfo.isMainFrame'));
console.log('PASS: no startup prompt; native get/watch/clear; timeout excludes authorization; denial; stale callbacks; page cleanup');
